FROM	 archlinux:latest
RUN	 pacman -Syy

RUN	 pacman -S --noconfirm openssh

# Generate host keys
RUN  /usr/bin/ssh-keygen -A
# Add password to root user
RUN	 echo 'root:root' | chpasswd

COPY sshd_config /etc/ssh/sshd_config

# Expose tcp port
EXPOSE	 22

# Run openssh daemon
#CMD	 ["/usr/sbin/sshd", "-D"]
