run:
  timeout: 10m
  modules-download-mode: readonly

output:
  format: tab
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Additional linters
    - exportloopref

    - bodyclose
    - errname
    - exportloopref
    - godot
    - gofmt
    - gofumpt
    - misspell
    - noctx
    - revive
    - tenv
    - unconvert
    - unparam

issues:
  max-issues-per-linter: 0
  max-same-issues: 20
  include:
    - EXC0012
    - EXC0014
  exclude-rules:

linters-settings:
  errcheck:
    # List of functions to exclude from checking, where each entry is a single function to exclude.
    # See https://github.com/kisielk/errcheck#excluding-functions for details.
    exclude-functions:
      - (*google.golang.org/grpc.Server).Serve
