FROM golang:1.20.1-bullseye
# Copy Repo
COPY go.mod /delegatio/
COPY go.sum /delegatio/

WORKDIR /delegatio
RUN go mod download

COPY ./ /delegatio

WORKDIR /delegatio/ssh
RUN go build -o ssh .

CMD /delegatio/ssh/ssh


