FROM golang:1.23.1-bullseye
# Copy Repo
COPY go.mod /delegatio/
COPY go.sum /delegatio/

WORKDIR /delegatio
RUN go mod download

COPY ./ /delegatio

WORKDIR /delegatio/ssh
RUN go build -o ssh .

FROM archlinux:latest
COPY --from=0 /delegatio/ssh/ssh /delegatio/ssh/ssh

RUN pacman -Syy

CMD /delegatio/ssh/ssh


