// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: gradeapi.proto

package gradeproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestGradingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExerciseId int32  `protobuf:"varint,1,opt,name=exerciseId,proto3" json:"exerciseId,omitempty"`
	StudentId  string `protobuf:"bytes,2,opt,name=studentId,proto3" json:"studentId,omitempty"`
	Solution   []byte `protobuf:"bytes,3,opt,name=solution,proto3" json:"solution,omitempty"`
	Signature  []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Submit     bool   `protobuf:"varint,5,opt,name=submit,proto3" json:"submit,omitempty"`
}

func (x *RequestGradingRequest) Reset() {
	*x = RequestGradingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradeapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGradingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGradingRequest) ProtoMessage() {}

func (x *RequestGradingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gradeapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGradingRequest.ProtoReflect.Descriptor instead.
func (*RequestGradingRequest) Descriptor() ([]byte, []int) {
	return file_gradeapi_proto_rawDescGZIP(), []int{0}
}

func (x *RequestGradingRequest) GetExerciseId() int32 {
	if x != nil {
		return x.ExerciseId
	}
	return 0
}

func (x *RequestGradingRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *RequestGradingRequest) GetSolution() []byte {
	if x != nil {
		return x.Solution
	}
	return nil
}

func (x *RequestGradingRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RequestGradingRequest) GetSubmit() bool {
	if x != nil {
		return x.Submit
	}
	return false
}

type RequestGradingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points int32  `protobuf:"varint,1,opt,name=points,proto3" json:"points,omitempty"`
	Log    []byte `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *RequestGradingResponse) Reset() {
	*x = RequestGradingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gradeapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGradingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGradingResponse) ProtoMessage() {}

func (x *RequestGradingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gradeapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGradingResponse.ProtoReflect.Descriptor instead.
func (*RequestGradingResponse) Descriptor() ([]byte, []int) {
	return file_gradeapi_proto_rawDescGZIP(), []int{1}
}

func (x *RequestGradingResponse) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *RequestGradingResponse) GetLog() []byte {
	if x != nil {
		return x.Log
	}
	return nil
}

var File_gradeapi_proto protoreflect.FileDescriptor

var file_gradeapi_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x22, 0xa7, 0x01, 0x0a, 0x15, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69,
	0x73, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x22, 0x42, 0x0a, 0x16, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47,
	0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x32, 0x5a, 0x0a, 0x03, 0x41, 0x50, 0x49, 0x12,
	0x53, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x72, 0x61, 0x64, 0x69, 0x6e,
	0x67, 0x12, 0x1f, 0x2e, 0x67, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x47, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x64, 0x65, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x6e, 0x73, 0x63, 0x68, 0x6c, 0x75, 0x65, 0x74, 0x65, 0x72, 0x2f,
	0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x2f, 0x67, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x2f, 0x67, 0x72, 0x61, 0x64, 0x65, 0x41, 0x50, 0x49, 0x2f, 0x67, 0x72, 0x61, 0x64, 0x65, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gradeapi_proto_rawDescOnce sync.Once
	file_gradeapi_proto_rawDescData = file_gradeapi_proto_rawDesc
)

func file_gradeapi_proto_rawDescGZIP() []byte {
	file_gradeapi_proto_rawDescOnce.Do(func() {
		file_gradeapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_gradeapi_proto_rawDescData)
	})
	return file_gradeapi_proto_rawDescData
}

var file_gradeapi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gradeapi_proto_goTypes = []interface{}{
	(*RequestGradingRequest)(nil),  // 0: gradeapi.RequestGradingRequest
	(*RequestGradingResponse)(nil), // 1: gradeapi.RequestGradingResponse
}
var file_gradeapi_proto_depIdxs = []int32{
	0, // 0: gradeapi.API.RequestGrading:input_type -> gradeapi.RequestGradingRequest
	1, // 1: gradeapi.API.RequestGrading:output_type -> gradeapi.RequestGradingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gradeapi_proto_init() }
func file_gradeapi_proto_init() {
	if File_gradeapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gradeapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGradingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gradeapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGradingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gradeapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gradeapi_proto_goTypes,
		DependencyIndexes: file_gradeapi_proto_depIdxs,
		MessageInfos:      file_gradeapi_proto_msgTypes,
	}.Build()
	File_gradeapi_proto = out.File
	file_gradeapi_proto_rawDesc = nil
	file_gradeapi_proto_goTypes = nil
	file_gradeapi_proto_depIdxs = nil
}
