// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: vmapi.proto

package vmproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_vmapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_vmapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_vmapi_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetJoinDataKubeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetJoinDataKubeRequest) Reset() {
	*x = GetJoinDataKubeRequest{}
	mi := &file_vmapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJoinDataKubeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinDataKubeRequest) ProtoMessage() {}

func (x *GetJoinDataKubeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinDataKubeRequest.ProtoReflect.Descriptor instead.
func (*GetJoinDataKubeRequest) Descriptor() ([]byte, []int) {
	return file_vmapi_proto_rawDescGZIP(), []int{1}
}

type JoinToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token             string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CaCertHash        string `protobuf:"bytes,2,opt,name=caCertHash,proto3" json:"caCertHash,omitempty"`
	ApiServerEndpoint string `protobuf:"bytes,3,opt,name=apiServerEndpoint,proto3" json:"apiServerEndpoint,omitempty"`
}

func (x *JoinToken) Reset() {
	*x = JoinToken{}
	mi := &file_vmapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToken) ProtoMessage() {}

func (x *JoinToken) ProtoReflect() protoreflect.Message {
	mi := &file_vmapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToken.ProtoReflect.Descriptor instead.
func (*JoinToken) Descriptor() ([]byte, []int) {
	return file_vmapi_proto_rawDescGZIP(), []int{2}
}

func (x *JoinToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinToken) GetCaCertHash() string {
	if x != nil {
		return x.CaCertHash
	}
	return ""
}

func (x *JoinToken) GetApiServerEndpoint() string {
	if x != nil {
		return x.ApiServerEndpoint
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_vmapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_vmapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_vmapi_proto_rawDescGZIP(), []int{3}
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetJoinDataKubeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoinToken *JoinToken `protobuf:"bytes,1,opt,name=joinToken,proto3" json:"joinToken,omitempty"`
	Files     []*File    `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *GetJoinDataKubeResponse) Reset() {
	*x = GetJoinDataKubeResponse{}
	mi := &file_vmapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJoinDataKubeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinDataKubeResponse) ProtoMessage() {}

func (x *GetJoinDataKubeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinDataKubeResponse.ProtoReflect.Descriptor instead.
func (*GetJoinDataKubeResponse) Descriptor() ([]byte, []int) {
	return file_vmapi_proto_rawDescGZIP(), []int{4}
}

func (x *GetJoinDataKubeResponse) GetJoinToken() *JoinToken {
	if x != nil {
		return x.JoinToken
	}
	return nil
}

func (x *GetJoinDataKubeResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type InitFirstMasterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Tty     bool     `protobuf:"varint,3,opt,name=tty,proto3" json:"tty,omitempty"`
}

func (x *InitFirstMasterRequest) Reset() {
	*x = InitFirstMasterRequest{}
	mi := &file_vmapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitFirstMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitFirstMasterRequest) ProtoMessage() {}

func (x *InitFirstMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vmapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitFirstMasterRequest.ProtoReflect.Descriptor instead.
func (*InitFirstMasterRequest) Descriptor() ([]byte, []int) {
	return file_vmapi_proto_rawDescGZIP(), []int{5}
}

func (x *InitFirstMasterRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *InitFirstMasterRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *InitFirstMasterRequest) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

type InitFirstMasterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//
	//	*InitFirstMasterResponse_Output
	//	*InitFirstMasterResponse_Log
	Content isInitFirstMasterResponse_Content `protobuf_oneof:"content"`
}

func (x *InitFirstMasterResponse) Reset() {
	*x = InitFirstMasterResponse{}
	mi := &file_vmapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitFirstMasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitFirstMasterResponse) ProtoMessage() {}

func (x *InitFirstMasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vmapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitFirstMasterResponse.ProtoReflect.Descriptor instead.
func (*InitFirstMasterResponse) Descriptor() ([]byte, []int) {
	return file_vmapi_proto_rawDescGZIP(), []int{6}
}

func (m *InitFirstMasterResponse) GetContent() isInitFirstMasterResponse_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *InitFirstMasterResponse) GetOutput() []byte {
	if x, ok := x.GetContent().(*InitFirstMasterResponse_Output); ok {
		return x.Output
	}
	return nil
}

func (x *InitFirstMasterResponse) GetLog() *Log {
	if x, ok := x.GetContent().(*InitFirstMasterResponse_Log); ok {
		return x.Log
	}
	return nil
}

type isInitFirstMasterResponse_Content interface {
	isInitFirstMasterResponse_Content()
}

type InitFirstMasterResponse_Output struct {
	Output []byte `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type InitFirstMasterResponse_Log struct {
	Log *Log `protobuf:"bytes,2,opt,name=log,proto3,oneof"`
}

func (*InitFirstMasterResponse_Output) isInitFirstMasterResponse_Content() {}

func (*InitFirstMasterResponse_Log) isInitFirstMasterResponse_Content() {}

var File_vmapi_proto protoreflect.FileDescriptor

var file_vmapi_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x76, 0x6d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76,
	0x6d, 0x61, 0x70, 0x69, 0x22, 0x1f, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x69, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x6f, 0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x43, 0x65, 0x72, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x43, 0x65, 0x72, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x2c, 0x0a, 0x11, 0x61, 0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61,
	0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x22, 0x34, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x6c, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x69,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2e, 0x0a, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x6d, 0x61, 0x70, 0x69, 0x2e, 0x4a, 0x6f, 0x69,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x21, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x76, 0x6d, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x22, 0x58, 0x0a, 0x16, 0x49, 0x6e, 0x69, 0x74, 0x46, 0x69, 0x72, 0x73,
	0x74, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x74, 0x74, 0x79, 0x22, 0x5e,
	0x0a, 0x17, 0x49, 0x6e, 0x69, 0x74, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x76, 0x6d, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x6f, 0x67, 0x48, 0x00, 0x52, 0x03,
	0x6c, 0x6f, 0x67, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x32, 0xab,
	0x01, 0x0a, 0x03, 0x41, 0x50, 0x49, 0x12, 0x50, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x69,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x62, 0x65, 0x12, 0x1d, 0x2e, 0x76, 0x6d, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x62,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x76, 0x6d, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x4b, 0x75, 0x62, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x0f, 0x49, 0x6e, 0x69, 0x74,
	0x46, 0x69, 0x72, 0x73, 0x74, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x76, 0x6d,
	0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x76, 0x6d, 0x61,
	0x70, 0x69, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x3a, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x6e, 0x73, 0x63,
	0x68, 0x6c, 0x75, 0x65, 0x74, 0x65, 0x72, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x6d, 0x2f, 0x76, 0x6d, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x6d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vmapi_proto_rawDescOnce sync.Once
	file_vmapi_proto_rawDescData = file_vmapi_proto_rawDesc
)

func file_vmapi_proto_rawDescGZIP() []byte {
	file_vmapi_proto_rawDescOnce.Do(func() {
		file_vmapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_vmapi_proto_rawDescData)
	})
	return file_vmapi_proto_rawDescData
}

var file_vmapi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_vmapi_proto_goTypes = []any{
	(*Log)(nil),                     // 0: vmapi.Log
	(*GetJoinDataKubeRequest)(nil),  // 1: vmapi.GetJoinDataKubeRequest
	(*JoinToken)(nil),               // 2: vmapi.JoinToken
	(*File)(nil),                    // 3: vmapi.File
	(*GetJoinDataKubeResponse)(nil), // 4: vmapi.GetJoinDataKubeResponse
	(*InitFirstMasterRequest)(nil),  // 5: vmapi.InitFirstMasterRequest
	(*InitFirstMasterResponse)(nil), // 6: vmapi.InitFirstMasterResponse
}
var file_vmapi_proto_depIdxs = []int32{
	2, // 0: vmapi.GetJoinDataKubeResponse.joinToken:type_name -> vmapi.JoinToken
	3, // 1: vmapi.GetJoinDataKubeResponse.files:type_name -> vmapi.File
	0, // 2: vmapi.InitFirstMasterResponse.log:type_name -> vmapi.Log
	1, // 3: vmapi.API.GetJoinDataKube:input_type -> vmapi.GetJoinDataKubeRequest
	5, // 4: vmapi.API.InitFirstMaster:input_type -> vmapi.InitFirstMasterRequest
	4, // 5: vmapi.API.GetJoinDataKube:output_type -> vmapi.GetJoinDataKubeResponse
	6, // 6: vmapi.API.InitFirstMaster:output_type -> vmapi.InitFirstMasterResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vmapi_proto_init() }
func file_vmapi_proto_init() {
	if File_vmapi_proto != nil {
		return
	}
	file_vmapi_proto_msgTypes[6].OneofWrappers = []any{
		(*InitFirstMasterResponse_Output)(nil),
		(*InitFirstMasterResponse_Log)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vmapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vmapi_proto_goTypes,
		DependencyIndexes: file_vmapi_proto_depIdxs,
		MessageInfos:      file_vmapi_proto_msgTypes,
	}.Build()
	File_vmapi_proto = out.File
	file_vmapi_proto_rawDesc = nil
	file_vmapi_proto_goTypes = nil
	file_vmapi_proto_depIdxs = nil
}
