// Code generated by "stringer -type=State"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Uninitialized-0]
	_ = x[AcceptingInit-1]
	_ = x[JoiningCluster-2]
	_ = x[Initialized-3]
	_ = x[Failed-4]
	_ = x[maxState-5]
}

const _State_name = "UninitializedAcceptingInitJoiningClusterInitializedFailedmaxState"

var _State_index = [...]uint8{0, 13, 26, 40, 51, 57, 65}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
