FROM golang:1.23.1-bullseye

COPY go.mod /delegatio/
COPY go.sum /delegatio/

WORKDIR /delegatio
RUN go mod download

COPY ./ /delegatio

WORKDIR /delegatio/agent/container
RUN go build -o agent .

WORKDIR /delegatio/grader/user
RUN go build -o agent-user .


FROM archlinux:latest

RUN useradd -d /home/user -s /bin/bash -u 1001 user

COPY --from=0 /delegatio/agent/container/agent /
COPY --from=0 /delegatio/grader/user/agent-user /
RUN	 pacman -Syy
#RUN	 pacman -Sy --noconfirm archlinux-keyring
#RUN	 pacman-key --refresh-keys
#RUN	 pacman -S --noconfirm go git gcc make cmake libvirt

USER user

CMD ["/agent", "--container", "--debug"]