[Distribution]
Distribution=arch

[Output]
Format=disk
Output=image
WorkspaceDirectory=/tmp
CacheDirectory=.cache

[Content]
Bootable=yes
Autologin=yes
KernelCommandLine=console=ttyS0,38400n8d
Bootloader=systemd-boot
Packages=
         openssh
         vim
         curl
         linux
         python
         
         socat
         ethtool
         conntrack-tools
         iptables-nft
         runc
         cri-o
         systemd

         nfs-utils