#!/usr/bin/env bash

systemctl enable systemd-networkd.service
systemctl enable systemd-resolved.service
systemctl enable kubelet.service
systemctl enable containerd.service
systemctl enable randomhost.service
systemctl enable delegatio-agent.service
systemctl enable systemd-sysctl.service
systemctl enable systemd-modules-load.service
ln -rsf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
