// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package vmproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIClient interface {
	ExecCommand(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (API_ExecCommandClient, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) ExecCommand(ctx context.Context, in *ExecCommandRequest, opts ...grpc.CallOption) (API_ExecCommandClient, error) {
	stream, err := c.cc.NewStream(ctx, &API_ServiceDesc.Streams[0], "/vmapi.API/ExecCommand", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIExecCommandClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_ExecCommandClient interface {
	Recv() (*ExecCommandResponse, error)
	grpc.ClientStream
}

type aPIExecCommandClient struct {
	grpc.ClientStream
}

func (x *aPIExecCommandClient) Recv() (*ExecCommandResponse, error) {
	m := new(ExecCommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility
type APIServer interface {
	ExecCommand(*ExecCommandRequest, API_ExecCommandServer) error
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (UnimplementedAPIServer) ExecCommand(*ExecCommandRequest, API_ExecCommandServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecCommand not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s grpc.ServiceRegistrar, srv APIServer) {
	s.RegisterService(&API_ServiceDesc, srv)
}

func _API_ExecCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).ExecCommand(m, &aPIExecCommandServer{stream})
}

type API_ExecCommandServer interface {
	Send(*ExecCommandResponse) error
	grpc.ServerStream
}

type aPIExecCommandServer struct {
	grpc.ServerStream
}

func (x *aPIExecCommandServer) Send(m *ExecCommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

// API_ServiceDesc is the grpc.ServiceDesc for API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmapi.API",
	HandlerType: (*APIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecCommand",
			Handler:       _API_ExecCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vmapi.proto",
}
